### ISSUE TITLE
May I ask what's the rate of progress of this project?

### ISSUE THREAD

**Issue by xionchen** [yac/pwnpkg#1]
May I ask what't the rate of progress of this project?
I have noticed that there are only doc here, will this project be developed?
It's mentioned that something has been done,Can I get involved in that code somewhere?

**Comment by TristanCacqueray** [comment]
+1, what's the status, can we help?! :)

@xionchen note that the rdopkg code is available here: https://review.rdoproject.org/r/rdopkg.git

**Comment by xionchen** [comment]
@TristanCacqueray I have kept a eye on rdopkg for a while, but thx anyway.

**Comment by yac** [comment]
Sorry to leave this hanging... I've decided not to split effort into two project and instead make `rdopkg` both a tool and a framework. Neccessary refactorings have been done and it's progressing real well... actually `rdopkg` is ready to start `fedpkg` effort.

I'll try to update the manifest accordingly.

**Comment by yac** [comment]
I've updated the README to match current status.

**Comment by yac** [comment]
To answer: Rate of progress is surprisingly good. Official support for CLIs is to be expected around `rdopkg-0.44` but when someone comes to me with a wish to rewrite `fedpkg` or so, I can rush the neccessary changes into next release ^^

Cheers!
